# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='open_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='open date'),
        ),
    ]
