# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0002_assignment_open_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
