# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0003_student_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_text',
            new_name='as_text',
        ),
        migrations.AddField(
            model_name='assignment',
            name='as_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
