# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0004_auto_20170831_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(default=None, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=64),
        ),
    ]
