# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 12:22
from __future__ import unicode_literals

import AutoGrade.models
import AutoGrade.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0005_auto_20170831_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_file', models.FileField(default=None, storage=AutoGrade.storage.OverwriteStorage(), upload_to=AutoGrade.models.other_files_directory_path)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Assignment')),
            ],
        ),
    ]
