# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 16:39
from __future__ import unicode_literals

import AutoGrade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0005_auto_20170826_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enroll_key',
            field=models.CharField(default=AutoGrade.models.enroll_key, max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='submission_pass',
            field=models.CharField(default=AutoGrade.models.submission_key, max_length=12),
        ),
    ]
