# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0007_auto_20170831_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherfile',
            old_name='other_file',
            new_name='file',
        ),
    ]
