# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0009_auto_20170826_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
