# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0009_auto_20170831_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('course', 'title')]),
        ),
    ]
