# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0011_student_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='percent',
        ),
    ]
