# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0011_student_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'queue'), ('1', 'executing'), ('2', 'done')], max_length=1)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('timeout', models.IntegerField(default=3)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Submission')),
            ],
        ),
    ]
