# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0012_submissionqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionqueue',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Submission'),
        ),
    ]
