# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0012_remove_submission_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='max_extension_days',
            field=models.IntegerField(default=0),
        ),
    ]
