# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0012_remove_submission_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDate_Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='due date')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='late_days',
            field=models.IntegerField(default=3),
        ),
    ]
