# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0013_auto_20170923_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_extension',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='request_extension',
            name='student',
        ),
        migrations.DeleteModel(
            name='Request_Extension',
        ),
    ]
