# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0014_auto_20170923_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='due date')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Student')),
            ],
        ),
    ]
