# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0015_request_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='allowed_late_days',
        ),
    ]
