# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0015_auto_20171026_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='test_input_type',
            field=models.CharField(choices=[('0', 'Pytest'), ('1', 'STDIN'), ('2', 'File')], default=0, max_length=1),
        ),
    ]
