# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0016_remove_assignment_allowed_late_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_extension',
            name='assignment',
            field=models.IntegerField(),
        ),
    ]
