# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0017_auto_20170923_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_extension',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoGrade.Assignment'),
        ),
    ]
