# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0018_auto_20170923_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='late_days',
        ),
        migrations.AddField(
            model_name='request_extension',
            name='late_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_sub',
            field=models.BooleanField(default=False),
        ),
    ]
