# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 18:21
from __future__ import unicode_literals

import AutoGrade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0008_auto_20170826_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enroll_key',
            field=models.CharField(default=AutoGrade.models.enroll_key, max_length=8, unique=True),
        ),
    ]
