# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0010_auto_20170828_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
