# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0011_submission_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='timeout',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_points',
            field=models.IntegerField(default=25),
        ),
    ]
