# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 16:07
from __future__ import unicode_literals

import AutoGrade.models
import AutoGrade.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGrade', '0014_auto_20170828_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_files',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(default=None, storage=AutoGrade.storage.OverwriteStorage(), upload_to=AutoGrade.models.assignment_directory_path),
        ),
    ]
